### DISCUSSION TITLE
How to work with array and objects in environment.yaml

### DISCUSSION THREAD

**Discussion by manishtiwari25** [Azure/deployment-environments#45] [Q&A]
Hey,
I am facing issues when I using array and object parameter  type, as mentioned [here ](https://learn.microsoft.com/en-us/azure/deployment-environments/concept-environment-yaml#parameter-definitions) these should be supported. 

catelog syncs but on dev portal these are coming as string fields. 

environment.yaml
```yaml
parameters: 
  - id: "name"
    name: "Name"
    required: true
    type: "string"
  - id: "address_space"
    name: "Address Spaces"
    required: true
    type: "array"
  - id: "dns_servers"
    name: "DNS Servers"
    required: false
    type: "array"
  - id: "subnets"
    name: "Subnets"
    required: true
    type: "object"
```

dev portal

![image](https://github.com/Azure/deployment-environments/assets/50008945/f4a3904d-8e43-4926-992d-b30d7d715ff8)
