### ISSUE TITLE
manifest.yaml differs from MS documentation

### ISSUE THREAD

**Issue by tkimmm** [Azure/deployment-environments#1]
https://learn.microsoft.com/en-gb/azure/deployment-environments/configure-catalog-item#add-a-new-catalog-item 

Indicates that the manifest.yaml should have the structure:

```
name: WebApp
    version: 1.0.0
    description: Deploys an Azure Web App without a data store
    engine:
      type: ARM
      templatePath: azuredeploy.json
```

However the manifests in this sample project follow the structure:

```
name: FunctionApp
version: 1.0.0
summary: Azure Function App Environment
description: Deploys an Azure Function App, Storage Account, and Application Insights
runner: ARM
templatePath: azuredeploy.json
```

Can open a PR if required, just need confirmation which is correct
