### ISSUE TITLE
[Developer Portal] parameters are not displayed when catalog items with parameters are selected

### ISSUE THREAD

**Issue by nb-atudose** [Azure/deployment-environments#5]
Instead of displaying the parameters for a catalog item that requires parameters, this message is shown: _This catalog item requires no parameter inputs, and will be created immediately._

![Screenshot from 2023-01-31 22-50-56](https://user-images.githubusercontent.com/86687374/215880407-b8fb724f-9723-4dd1-b870-ec345d418bd0.png)

The catalog item does require parameters:
![Screenshot from 2023-01-31 22-53-12](https://user-images.githubusercontent.com/86687374/215880620-c684c076-462b-46cc-990a-d5b1da0cb6b6.png)

Deploying from az cli works as expected.

**Comment by ericaguthan** [comment]
Hi @nb-atudose! The reason for this the UI creation scenario is only able to know about parameters specified in the manifest file. If you add the parameters that you see in the ARM template to the manifest, that data can be input via the UI.

**Comment by j-rewerts** [comment]
Here is an example of a manifest.yml with some basic parameters:

``` yaml
name: AppConfig
summary: This is an App Configuration deployment.
description: Deploys an App Config.
templatePath: azuredeploy.json
parameters:
- id: "name"
  name: "name"
  description: "Name of the App Config"
  default: ""
  type: "string"
  required: false
- id: "location"
  name: "location"
  description: "Location to deploy the environment resources"
  default: "[resourceGroup().location]"
  type: "string"
  required: false
runner: arm
```
